/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggggght_feature_ParametersJNI */

#ifndef _Included_com_ggggght_feature_ParametersJNI
#define _Included_com_ggggght_feature_ParametersJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggggght_feature_ParametersJNI
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_ggggght_feature_ParametersJNI_sumIntegers
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_ggggght_feature_ParametersJNI
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ggggght_feature_ParametersJNI_sayHelloToMe
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
