/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
#include "com_ggggght_feature_ParametersJNI.h"

/*
 * Class:     com_ggggght_feature_ParametersJNI
 * Method:    sumIntegers
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_ggggght_feature_ParametersJNI_sumIntegers
  (JNIEnv* env, jobject thisObject, jint first, jint second) {
    std::cout << "C++: The numbers received are : " << first << " and " << second << std::endl;
    return (long)first + (long)second;
  }

/*
 * Class:     com_ggggght_feature_ParametersJNI
 * Method:    sayHelloToMe
 * Signature: (Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ggggght_feature_ParametersJNI_sayHelloToMe
  (JNIEnv* env, jobject thisObject, jstring name, jboolean isFemale) {
    const char* nameCharPointer = env->GetStringUTFChars(name, NULL);
        std::cout << "C++: The string received is: " << nameCharPointer << std::endl;
        std::string title;
        if(isFemale){
            title = "Ms. ";
        }
        else{
            title = "Mr. ";
        }

        std::string fullName = title + nameCharPointer;
        return env->NewStringUTF(fullName.c_str());
  }


