/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggggght_object_ExampleObjectsJNI */

#ifndef _Included_com_ggggght_object_ExampleObjectsJNI
#define _Included_com_ggggght_object_ExampleObjectsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggggght_object_ExampleObjectsJNI
 * Method:    createUser
 * Signature: (Ljava/lang/String;D)Lcom/ggggght/object/UserData;
 */
JNIEXPORT jobject JNICALL Java_com_ggggght_object_ExampleObjectsJNI_createUser
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_ggggght_object_ExampleObjectsJNI
 * Method:    printUserData
 * Signature: (Lcom/ggggght/object/UserData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ggggght_object_ExampleObjectsJNI_printUserData
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
