/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
/* Header for class com_ggggght_HelloWorld */

//#ifndef _Included_com_ggggght_HelloWorld
//#define _Included_com_ggggght_HelloWorld
//#ifdef __cplusplus
//extern "C" {
//#endif

JNIEXPORT void JNICALL Java_com_baeldung_jni_HelloWorldJNI_sayHello
  (JNIEnv* env, jobject thisObject) {
    std::cout << "Hello from C++ !!" << std::endl;
}

//#ifdef __cplusplus
//}
//#endif
//#endif
