/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ggggght_HelloWorld */

#ifndef _Included_com_ggggght_HelloWorld
#define _Included_com_ggggght_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ggggght_HelloWorld
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ggggght_HelloWorld_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
